import React, { useState } from 'react';
import RiverCrossing from './components/RiverCrossing';
import BrokenCalculator from './components/BrokenCalculator';
import LogicFriends from './components/LogicFriends';
import RiddleBot from './components/RiddleBot';
import ActivityCard from './components/ActivityCard';
import { ArrowLeft, Brain, Calculator, Ship, Users, HelpCircle, Construction, Map as MapIcon, Puzzle } from 'lucide-react';
import { ExerciseType, Activity } from './types';

const ACTIVITIES: Activity[] = [
  {
    id: 'river',
    title: 'River Crossing',
    type: ExerciseType.RIVER_CROSSING,
    icon: '🚣‍♂️',
    description: 'Help the farmer, wolf, goat, and cabbage cross safely!',
    difficulty: 'Medium'
  },
  {
    id: 'calc',
    title: 'Broken Calculator',
    type: ExerciseType.BROKEN_CALCULATOR,
    icon: '🧮',
    description: 'Can you make 25 without pressing the number 5?',
    difficulty: 'Hard'
  },
  {
    id: 'logic',
    title: 'Logic Friends',
    type: ExerciseType.LOGIC_FRIENDS,
    icon: '👕',
    description: 'Who is wearing which shirt color? Use the clues!',
    difficulty: 'Medium'
  },
  {
    id: 'riddle',
    title: 'Riddle Robot',
    type: ExerciseType.RIDDLES,
    icon: '🤖',
    description: 'Solve fun riddles generated by AI.',
    difficulty: 'Easy'
  },
  {
    id: 'marshmallow',
    title: 'Marshmallow Tower',
    type: ExerciseType.ACTIVITY_CARD,
    icon: '🗼',
    description: 'A physical engineering challenge.',
    difficulty: 'Hard'
  },
  {
    id: 'map',
    title: 'Map The House',
    type: ExerciseType.ACTIVITY_CARD,
    icon: '🗺️',
    description: 'Draw a treasure map of your room!',
    difficulty: 'Easy'
  }
];

const App: React.FC = () => {
  const [activeActivity, setActiveActivity] = useState<string | null>(null);

  const renderContent = () => {
    switch (activeActivity) {
      case 'river': return <RiverCrossing />;
      case 'calc': return <BrokenCalculator />;
      case 'logic': return <LogicFriends />;
      case 'riddle': return <RiddleBot />;
      case 'marshmallow': 
        return <ActivityCard 
            title="Marshmallow Challenge" 
            description="Engineering time! Can you fight gravity?" 
            materials={['20 sticks of spaghetti', '1 yard of tape', '1 yard of string', '1 marshmallow']}
            challenge="Build the tallest freestanding structure that can hold the marshmallow on top!"
        />;
      case 'map':
        return <ActivityCard 
            title="Treasure Map"
            description="Learn to see the world from a bird's eye view."
            materials={['Paper', 'Crayons', 'A small toy to hide']}
            challenge="Draw a map of your room looking down from the ceiling. Hide a toy, mark 'X' on the map, and see if someone can find it!"
        />;
      default: return null;
    }
  };

  if (activeActivity) {
    return (
      <div className="min-h-screen bg-sky-50 p-4">
        <button 
          onClick={() => setActiveActivity(null)}
          className="mb-4 flex items-center gap-2 text-sky-700 font-bold hover:bg-sky-100 p-2 rounded-lg transition-colors"
        >
          <ArrowLeft /> Back to Playground
        </button>
        <div className="animate-fade-in-up">
            {renderContent()}
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-sky-100 to-green-50 p-6 md:p-12">
      <header className="text-center mb-12">
        <h1 className="text-5xl md:text-6xl font-comic-font font-bold text-sky-600 mb-4 drop-shadow-sm flex items-center justify-center gap-4">
            <Brain className="w-12 h-12 md:w-16 md:h-16 text-yellow-500" />
            Brainy Builders
        </h1>
        <p className="text-xl text-sky-800 font-medium opacity-80 max-w-2xl mx-auto">
            Pick a challenge to stretch your brain muscles! 🚀
        </p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
        {ACTIVITIES.map((activity) => (
          <button
            key={activity.id}
            onClick={() => setActiveActivity(activity.id)}
            className="group relative bg-white rounded-3xl p-6 shadow-xl hover:shadow-2xl hover:-translate-y-2 transition-all duration-300 border-4 border-transparent hover:border-sky-300 text-left flex flex-col h-full"
          >
            <div className="text-6xl mb-4 group-hover:scale-110 transition-transform duration-300 w-20 h-20 flex items-center justify-center bg-gray-50 rounded-2xl">
                {activity.icon}
            </div>
            
            <h3 className="text-2xl font-bold text-gray-800 mb-2">{activity.title}</h3>
            <p className="text-gray-600 mb-4 flex-grow">{activity.description}</p>
            
            <div className="flex justify-between items-center mt-auto">
                <span className={`px-3 py-1 rounded-full text-sm font-bold 
                    ${activity.difficulty === 'Easy' ? 'bg-green-100 text-green-700' : 
                      activity.difficulty === 'Medium' ? 'bg-yellow-100 text-yellow-700' : 
                      'bg-red-100 text-red-700'}`}>
                    {activity.difficulty}
                </span>
                <span className="text-sky-500 font-bold group-hover:translate-x-1 transition-transform">Play →</span>
            </div>
          </button>
        ))}
      </div>
      
      <footer className="text-center mt-16 text-sky-900/40 font-medium">
        Made for Super Smart 3rd Graders 🌟
      </footer>
    </div>
  );
};

export default App;
